/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Reseplaneraren);
  }
}(this, function(expect, Reseplaneraren) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Reseplaneraren.Departure();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Departure', function() {
    it('should create an instance of Departure', function() {
      // uncomment below and update the code to test Departure
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be.a(Reseplaneraren.Departure);
    });

    it('should have the property fgColor (base name: "fgColor")', function() {
      // uncomment below and update the code to test the property fgColor
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property stop (base name: "stop")', function() {
      // uncomment below and update the code to test the property stop
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property booking (base name: "booking")', function() {
      // uncomment below and update the code to test the property booking
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property direction (base name: "direction")', function() {
      // uncomment below and update the code to test the property direction
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property journeyDetailRef (base name: "JourneyDetailRef")', function() {
      // uncomment below and update the code to test the property journeyDetailRef
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property track (base name: "track")', function() {
      // uncomment below and update the code to test the property track
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property rtTrack (base name: "rtTrack")', function() {
      // uncomment below and update the code to test the property rtTrack
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property sname (base name: "sname")', function() {
      // uncomment below and update the code to test the property sname
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property _date (base name: "date")', function() {
      // uncomment below and update the code to test the property _date
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property bgColor (base name: "bgColor")', function() {
      // uncomment below and update the code to test the property bgColor
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property stroke (base name: "stroke")', function() {
      // uncomment below and update the code to test the property stroke
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property rtDate (base name: "rtDate")', function() {
      // uncomment below and update the code to test the property rtDate
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property time (base name: "time")', function() {
      // uncomment below and update the code to test the property time
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property rtTime (base name: "rtTime")', function() {
      // uncomment below and update the code to test the property rtTime
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property night (base name: "night")', function() {
      // uncomment below and update the code to test the property night
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property stopid (base name: "stopid")', function() {
      // uncomment below and update the code to test the property stopid
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property journeyid (base name: "journeyid")', function() {
      // uncomment below and update the code to test the property journeyid
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

    it('should have the property accessibility (base name: "accessibility")', function() {
      // uncomment below and update the code to test the property accessibility
      //var instane = new Reseplaneraren.Departure();
      //expect(instance).to.be();
    });

  });

}));
