/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Reseplaneraren);
  }
}(this, function(expect, Reseplaneraren) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Reseplaneraren.Origin();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Origin', function() {
    it('should create an instance of Origin', function() {
      // uncomment below and update the code to test Origin
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be.a(Reseplaneraren.Origin);
    });

    it('should have the property routeIdx (base name: "routeIdx")', function() {
      // uncomment below and update the code to test the property routeIdx
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "$")', function() {
      // uncomment below and update the code to test the property value
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be();
    });

    it('should have the property cancelled (base name: "cancelled")', function() {
      // uncomment below and update the code to test the property cancelled
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be();
    });

    it('should have the property track (base name: "track")', function() {
      // uncomment below and update the code to test the property track
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be();
    });

    it('should have the property rtTrack (base name: "rtTrack")', function() {
      // uncomment below and update the code to test the property rtTrack
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be();
    });

    it('should have the property _date (base name: "date")', function() {
      // uncomment below and update the code to test the property _date
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be();
    });

    it('should have the property notes (base name: "Notes")', function() {
      // uncomment below and update the code to test the property notes
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be();
    });

    it('should have the property rtDate (base name: "rtDate")', function() {
      // uncomment below and update the code to test the property rtDate
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be();
    });

    it('should have the property time (base name: "time")', function() {
      // uncomment below and update the code to test the property time
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be();
    });

    it('should have the property directdate (base name: "directdate")', function() {
      // uncomment below and update the code to test the property directdate
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be();
    });

    it('should have the property rtTime (base name: "rtTime")', function() {
      // uncomment below and update the code to test the property rtTime
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be();
    });

    it('should have the property directtime (base name: "directtime")', function() {
      // uncomment below and update the code to test the property directtime
      //var instane = new Reseplaneraren.Origin();
      //expect(instance).to.be();
    });

  });

}));
