/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PlaneraResa);
  }
}(this, function(expect, PlaneraResa) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel', function() {
    it('should create an instance of VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel', function() {
      // uncomment below and update the code to test VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel();
      //expect(instance).to.be.a(PlaneraResa.VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel);
    });

    it('should have the property detailsReference (base name: "detailsReference")', function() {
      // uncomment below and update the code to test the property detailsReference
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel();
      //expect(instance).to.be();
    });

    it('should have the property serviceJourney (base name: "serviceJourney")', function() {
      // uncomment below and update the code to test the property serviceJourney
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel();
      //expect(instance).to.be();
    });

    it('should have the property stopPoint (base name: "stopPoint")', function() {
      // uncomment below and update the code to test the property stopPoint
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel();
      //expect(instance).to.be();
    });

    it('should have the property plannedTime (base name: "plannedTime")', function() {
      // uncomment below and update the code to test the property plannedTime
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel();
      //expect(instance).to.be();
    });

    it('should have the property estimatedTime (base name: "estimatedTime")', function() {
      // uncomment below and update the code to test the property estimatedTime
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel();
      //expect(instance).to.be();
    });

    it('should have the property estimatedOtherwisePlannedTime (base name: "estimatedOtherwisePlannedTime")', function() {
      // uncomment below and update the code to test the property estimatedOtherwisePlannedTime
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel();
      //expect(instance).to.be();
    });

    it('should have the property isCancelled (base name: "isCancelled")', function() {
      // uncomment below and update the code to test the property isCancelled
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel();
      //expect(instance).to.be();
    });

    it('should have the property isPartCancelled (base name: "isPartCancelled")', function() {
      // uncomment below and update the code to test the property isPartCancelled
      //var instance = new PlaneraResa.VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel();
      //expect(instance).to.be();
    });

  });

}));
