/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Reseplaneraren) {
      root.Reseplaneraren = {};
    }
    root.Reseplaneraren.Color = factory(root.Reseplaneraren.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Color model module.
   * @module model/Color
   * @version 1.10.1
   */

  /**
   * Constructs a new <code>Color</code>.
   * @alias module:model/Color
   * @class
   * @param bgColor {String} Backgroundcolor of this line
   * @param fgColor {String} Foregroundcolor of this line
   * @param stroke {String} Stroke style of this line
   */
  var exports = function(bgColor, fgColor, stroke) {
    var _this = this;

    _this['bgColor'] = bgColor;
    _this['fgColor'] = fgColor;
    _this['stroke'] = stroke;
  };

  /**
   * Constructs a <code>Color</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Color} obj Optional instance to populate.
   * @return {module:model/Color} The populated <code>Color</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('bgColor')) {
        obj['bgColor'] = ApiClient.convertToType(data['bgColor'], 'String');
      }
      if (data.hasOwnProperty('fgColor')) {
        obj['fgColor'] = ApiClient.convertToType(data['fgColor'], 'String');
      }
      if (data.hasOwnProperty('stroke')) {
        obj['stroke'] = ApiClient.convertToType(data['stroke'], 'String');
      }
    }
    return obj;
  }

  /**
   * Backgroundcolor of this line
   * @member {String} bgColor
   */
  exports.prototype['bgColor'] = undefined;
  /**
   * Foregroundcolor of this line
   * @member {String} fgColor
   */
  exports.prototype['fgColor'] = undefined;
  /**
   * Stroke style of this line
   * @member {String} stroke
   */
  exports.prototype['stroke'] = undefined;



  return exports;
}));


