/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Reseplaneraren) {
      root.Reseplaneraren = {};
    }
    root.Reseplaneraren.GeometryRef = factory(root.Reseplaneraren.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GeometryRef model module.
   * @module model/GeometryRef
   * @version 1.10.1
   */

  /**
   * Constructs a new <code>GeometryRef</code>.
   * @alias module:model/GeometryRef
   * @class
   * @param ref {String} Contains a URL to call the REST interface for geometry
   */
  var exports = function(ref) {
    var _this = this;

    _this['ref'] = ref;
  };

  /**
   * Constructs a <code>GeometryRef</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GeometryRef} obj Optional instance to populate.
   * @return {module:model/GeometryRef} The populated <code>GeometryRef</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ref')) {
        obj['ref'] = ApiClient.convertToType(data['ref'], 'String');
      }
    }
    return obj;
  }

  /**
   * Contains a URL to call the REST interface for geometry
   * @member {String} ref
   */
  exports.prototype['ref'] = undefined;



  return exports;
}));


