/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DateBegin', 'model/DateEnd'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DateBegin'), require('./DateEnd'));
  } else {
    // Browser globals (root is window)
    if (!root.Reseplaneraren) {
      root.Reseplaneraren = {};
    }
    root.Reseplaneraren.TimeTablePeriod = factory(root.Reseplaneraren.ApiClient, root.Reseplaneraren.DateBegin, root.Reseplaneraren.DateEnd);
  }
}(this, function(ApiClient, DateBegin, DateEnd) {
  'use strict';




  /**
   * The TimeTablePeriod model module.
   * @module model/TimeTablePeriod
   * @version 1.10.1
   */

  /**
   * Constructs a new <code>TimeTablePeriod</code>.
   * @alias module:model/TimeTablePeriod
   * @class
   * @param dateBegin {module:model/DateBegin} 
   * @param dateEnd {module:model/DateEnd} 
   */
  var exports = function(dateBegin, dateEnd) {
    var _this = this;

    _this['DateBegin'] = dateBegin;
    _this['DateEnd'] = dateEnd;
  };

  /**
   * Constructs a <code>TimeTablePeriod</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TimeTablePeriod} obj Optional instance to populate.
   * @return {module:model/TimeTablePeriod} The populated <code>TimeTablePeriod</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('DateBegin')) {
        obj['DateBegin'] = DateBegin.constructFromObject(data['DateBegin']);
      }
      if (data.hasOwnProperty('DateEnd')) {
        obj['DateEnd'] = DateEnd.constructFromObject(data['DateEnd']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/DateBegin} DateBegin
   */
  exports.prototype['DateBegin'] = undefined;
  /**
   * @member {module:model/DateEnd} DateEnd
   */
  exports.prototype['DateEnd'] = undefined;



  return exports;
}));


