/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TimeTableData', 'model/TimeTablePeriod'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TimeTableData'), require('./TimeTablePeriod'));
  } else {
    // Browser globals (root is window)
    if (!root.Reseplaneraren) {
      root.Reseplaneraren = {};
    }
    root.Reseplaneraren.TimetableInfo = factory(root.Reseplaneraren.ApiClient, root.Reseplaneraren.TimeTableData, root.Reseplaneraren.TimeTablePeriod);
  }
}(this, function(ApiClient, TimeTableData, TimeTablePeriod) {
  'use strict';




  /**
   * The TimetableInfo model module.
   * @module model/TimetableInfo
   * @version 1.10.1
   */

  /**
   * Constructs a new <code>TimetableInfo</code>.
   * @alias module:model/TimetableInfo
   * @class
   * @param timeTableData {module:model/TimeTableData} 
   * @param timeTablePeriod {module:model/TimeTablePeriod} 
   */
  var exports = function(timeTableData, timeTablePeriod) {
    var _this = this;

    _this['TimeTableData'] = timeTableData;
    _this['TimeTablePeriod'] = timeTablePeriod;
  };

  /**
   * Constructs a <code>TimetableInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TimetableInfo} obj Optional instance to populate.
   * @return {module:model/TimetableInfo} The populated <code>TimetableInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('TimeTableData')) {
        obj['TimeTableData'] = TimeTableData.constructFromObject(data['TimeTableData']);
      }
      if (data.hasOwnProperty('TimeTablePeriod')) {
        obj['TimeTablePeriod'] = TimeTablePeriod.constructFromObject(data['TimeTablePeriod']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/TimeTableData} TimeTableData
   */
  exports.prototype['TimeTableData'] = undefined;
  /**
   * @member {module:model/TimeTablePeriod} TimeTablePeriod
   */
  exports.prototype['TimeTablePeriod'] = undefined;



  return exports;
}));


