/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VTApiPlaneraResaCoreModelsTimeLimitation from './VTApiPlaneraResaCoreModelsTimeLimitation';
import VTApiPlaneraResaCoreModelsTravellerCategory from './VTApiPlaneraResaCoreModelsTravellerCategory';
import VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel from './VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel';
import VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel from './VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel';
import VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel from './VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel';
import VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel from './VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel';
import VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel from './VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel';

/**
 * The VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel model module.
 * @module model/VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
 * @version v4
 */
class VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel {
    /**
     * Constructs a new <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel</code>.
     * Information about a ticket suggestion.
     * @alias module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
     */
    constructor() { 
        
        VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel} obj Optional instance to populate.
     * @return {module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel} The populated <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel();

            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
            }
            if (data.hasOwnProperty('productName')) {
                obj['productName'] = ApiClient.convertToType(data['productName'], 'String');
            }
            if (data.hasOwnProperty('productType')) {
                obj['productType'] = ApiClient.convertToType(data['productType'], 'Number');
            }
            if (data.hasOwnProperty('travellerCategory')) {
                obj['travellerCategory'] = VTApiPlaneraResaCoreModelsTravellerCategory.constructFromObject(data['travellerCategory']);
            }
            if (data.hasOwnProperty('priceInSek')) {
                obj['priceInSek'] = ApiClient.convertToType(data['priceInSek'], 'Number');
            }
            if (data.hasOwnProperty('timeValidity')) {
                obj['timeValidity'] = VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel.constructFromObject(data['timeValidity']);
            }
            if (data.hasOwnProperty('timeLimitation')) {
                obj['timeLimitation'] = VTApiPlaneraResaCoreModelsTimeLimitation.constructFromObject(data['timeLimitation']);
            }
            if (data.hasOwnProperty('saleChannels')) {
                obj['saleChannels'] = ApiClient.convertToType(data['saleChannels'], [VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel]);
            }
            if (data.hasOwnProperty('validZones')) {
                obj['validZones'] = ApiClient.convertToType(data['validZones'], [VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel]);
            }
            if (data.hasOwnProperty('productInstanceType')) {
                obj['productInstanceType'] = VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel.constructFromObject(data['productInstanceType']);
            }
            if (data.hasOwnProperty('punchConfiguration')) {
                obj['punchConfiguration'] = VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel.constructFromObject(data['punchConfiguration']);
            }
            if (data.hasOwnProperty('offerSpecification')) {
                obj['offerSpecification'] = ApiClient.convertToType(data['offerSpecification'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['productName'] && !(typeof data['productName'] === 'string' || data['productName'] instanceof String)) {
            throw new Error("Expected the field `productName` to be a primitive type in the JSON string but got " + data['productName']);
        }
        // validate the optional field `timeValidity`
        if (data['timeValidity']) { // data not null
          VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel.validateJSON(data['timeValidity']);
        }
        if (data['saleChannels']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['saleChannels'])) {
                throw new Error("Expected the field `saleChannels` to be an array in the JSON data but got " + data['saleChannels']);
            }
            // validate the optional field `saleChannels` (array)
            for (const item of data['saleChannels']) {
                VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel.validateJSON(item);
            };
        }
        if (data['validZones']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['validZones'])) {
                throw new Error("Expected the field `validZones` to be an array in the JSON data but got " + data['validZones']);
            }
            // validate the optional field `validZones` (array)
            for (const item of data['validZones']) {
                VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel.validateJSON(item);
            };
        }
        // validate the optional field `punchConfiguration`
        if (data['punchConfiguration']) { // data not null
          VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel.validateJSON(data['punchConfiguration']);
        }
        // ensure the json data is a string
        if (data['offerSpecification'] && !(typeof data['offerSpecification'] === 'string' || data['offerSpecification'] instanceof String)) {
            throw new Error("Expected the field `offerSpecification` to be a primitive type in the JSON string but got " + data['offerSpecification']);
        }

        return true;
    }


}



/**
 * The product id.
 * @member {Number} productId
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel.prototype['productId'] = undefined;

/**
 * The product name.
 * @member {String} productName
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel.prototype['productName'] = undefined;

/**
 * The product type.
 * @member {Number} productType
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel.prototype['productType'] = undefined;

/**
 * @member {module:model/VTApiPlaneraResaCoreModelsTravellerCategory} travellerCategory
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel.prototype['travellerCategory'] = undefined;

/**
 * The product price in SEK.
 * @member {Number} priceInSek
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel.prototype['priceInSek'] = undefined;

/**
 * @member {module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel} timeValidity
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel.prototype['timeValidity'] = undefined;

/**
 * @member {module:model/VTApiPlaneraResaCoreModelsTimeLimitation} timeLimitation
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel.prototype['timeLimitation'] = undefined;

/**
 * A list of the channels that sell the product.
 * @member {Array.<module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel>} saleChannels
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel.prototype['saleChannels'] = undefined;

/**
 * A list of the valid zones for the ticket.
 * @member {Array.<module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel>} validZones
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel.prototype['validZones'] = undefined;

/**
 * @member {module:model/VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel} productInstanceType
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel.prototype['productInstanceType'] = undefined;

/**
 * @member {module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel} punchConfiguration
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel.prototype['punchConfiguration'] = undefined;

/**
 * Used to get ticket offer.
 * @member {String} offerSpecification
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel.prototype['offerSpecification'] = undefined;






export default VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel;

