/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver.
* @enum {}
* @readonly
*/
export default class VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver {
    
        /**
         * value: "none"
         * @const
         */
        "none" = "none";

    
        /**
         * value: "from"
         * @const
         */
        "from" = "from";

    
        /**
         * value: "to"
         * @const
         */
        "to" = "to";

    
        /**
         * value: "on"
         * @const
         */
        "on" = "on";

    
        /**
         * value: "left"
         * @const
         */
        "left" = "left";

    
        /**
         * value: "right"
         * @const
         */
        "right" = "right";

    
        /**
         * value: "keepleft"
         * @const
         */
        "keepleft" = "keepleft";

    
        /**
         * value: "keepright"
         * @const
         */
        "keepright" = "keepright";

    
        /**
         * value: "halfleft"
         * @const
         */
        "halfleft" = "halfleft";

    
        /**
         * value: "halfright"
         * @const
         */
        "halfright" = "halfright";

    
        /**
         * value: "keephalfleft"
         * @const
         */
        "keephalfleft" = "keephalfleft";

    
        /**
         * value: "keephalfright"
         * @const
         */
        "keephalfright" = "keephalfright";

    
        /**
         * value: "sharpleft"
         * @const
         */
        "sharpleft" = "sharpleft";

    
        /**
         * value: "sharpright"
         * @const
         */
        "sharpright" = "sharpright";

    
        /**
         * value: "keepsharpleft"
         * @const
         */
        "keepsharpleft" = "keepsharpleft";

    
        /**
         * value: "keepsharpright"
         * @const
         */
        "keepsharpright" = "keepsharpright";

    
        /**
         * value: "straight"
         * @const
         */
        "straight" = "straight";

    
        /**
         * value: "uturn"
         * @const
         */
        "uturn" = "uturn";

    
        /**
         * value: "enter"
         * @const
         */
        "enter" = "enter";

    
        /**
         * value: "leave"
         * @const
         */
        "leave" = "leave";

    
        /**
         * value: "enterroundabout"
         * @const
         */
        "enterroundabout" = "enterroundabout";

    
        /**
         * value: "stayinroundabout"
         * @const
         */
        "stayinroundabout" = "stayinroundabout";

    
        /**
         * value: "leaveroundabout"
         * @const
         */
        "leaveroundabout" = "leaveroundabout";

    
        /**
         * value: "enterferry"
         * @const
         */
        "enterferry" = "enterferry";

    
        /**
         * value: "leaveferry"
         * @const
         */
        "leaveferry" = "leaveferry";

    
        /**
         * value: "changehighway"
         * @const
         */
        "changehighway" = "changehighway";

    
        /**
         * value: "checkinferry"
         * @const
         */
        "checkinferry" = "checkinferry";

    
        /**
         * value: "checkoutferry"
         * @const
         */
        "checkoutferry" = "checkoutferry";

    
        /**
         * value: "elevator"
         * @const
         */
        "elevator" = "elevator";

    
        /**
         * value: "elevatordown"
         * @const
         */
        "elevatordown" = "elevatordown";

    
        /**
         * value: "elevatorup"
         * @const
         */
        "elevatorup" = "elevatorup";

    
        /**
         * value: "escalator"
         * @const
         */
        "escalator" = "escalator";

    
        /**
         * value: "escalatordown"
         * @const
         */
        "escalatordown" = "escalatordown";

    
        /**
         * value: "escalatorup"
         * @const
         */
        "escalatorup" = "escalatorup";

    
        /**
         * value: "stairs"
         * @const
         */
        "stairs" = "stairs";

    
        /**
         * value: "stairsdown"
         * @const
         */
        "stairsdown" = "stairsdown";

    
        /**
         * value: "stairsup"
         * @const
         */
        "stairsup" = "stairsup";

    

    /**
    * Returns a <code>VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver} The enum <code>VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

