/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VTApiPlaneraResaWebV4ModelsPaginationLinks model module.
 * @module model/VTApiPlaneraResaWebV4ModelsPaginationLinks
 * @version v4
 */
class VTApiPlaneraResaWebV4ModelsPaginationLinks {
    /**
     * Constructs a new <code>VTApiPlaneraResaWebV4ModelsPaginationLinks</code>.
     * Pagination navigation links.
     * @alias module:model/VTApiPlaneraResaWebV4ModelsPaginationLinks
     */
    constructor() { 
        
        VTApiPlaneraResaWebV4ModelsPaginationLinks.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VTApiPlaneraResaWebV4ModelsPaginationLinks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VTApiPlaneraResaWebV4ModelsPaginationLinks} obj Optional instance to populate.
     * @return {module:model/VTApiPlaneraResaWebV4ModelsPaginationLinks} The populated <code>VTApiPlaneraResaWebV4ModelsPaginationLinks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VTApiPlaneraResaWebV4ModelsPaginationLinks();

            if (data.hasOwnProperty('previous')) {
                obj['previous'] = ApiClient.convertToType(data['previous'], 'String');
            }
            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String');
            }
            if (data.hasOwnProperty('current')) {
                obj['current'] = ApiClient.convertToType(data['current'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VTApiPlaneraResaWebV4ModelsPaginationLinks</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VTApiPlaneraResaWebV4ModelsPaginationLinks</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['previous'] && !(typeof data['previous'] === 'string' || data['previous'] instanceof String)) {
            throw new Error("Expected the field `previous` to be a primitive type in the JSON string but got " + data['previous']);
        }
        // ensure the json data is a string
        if (data['next'] && !(typeof data['next'] === 'string' || data['next'] instanceof String)) {
            throw new Error("Expected the field `next` to be a primitive type in the JSON string but got " + data['next']);
        }
        // ensure the json data is a string
        if (data['current'] && !(typeof data['current'] === 'string' || data['current'] instanceof String)) {
            throw new Error("Expected the field `current` to be a primitive type in the JSON string but got " + data['current']);
        }

        return true;
    }


}



/**
 * Link to the previous results page, if available, otherwise null.
 * @member {String} previous
 */
VTApiPlaneraResaWebV4ModelsPaginationLinks.prototype['previous'] = undefined;

/**
 * Link to the next results page, if available, otherwise null. Not guaranteed to give a result if called.
 * @member {String} next
 */
VTApiPlaneraResaWebV4ModelsPaginationLinks.prototype['next'] = undefined;

/**
 * Link to the current results page, if available, otherwise null. Not guaranteed to give a result if called.
 * @member {String} current
 */
VTApiPlaneraResaWebV4ModelsPaginationLinks.prototype['current'] = undefined;






export default VTApiPlaneraResaWebV4ModelsPaginationLinks;

