/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VTApiPlaneraResaCoreModelsNote from './VTApiPlaneraResaCoreModelsNote';
import VTApiPlaneraResaWebV4ModelsPositionsLineDetailsApiModel from './VTApiPlaneraResaWebV4ModelsPositionsLineDetailsApiModel';

/**
 * The VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel model module.
 * @module model/VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel
 * @version v4
 */
class VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel {
    /**
     * Constructs a new <code>VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel</code>.
     * @alias module:model/VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel
     */
    constructor() { 
        
        VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel} obj Optional instance to populate.
     * @return {module:model/VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel} The populated <code>VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel();

            if (data.hasOwnProperty('detailsReference')) {
                obj['detailsReference'] = ApiClient.convertToType(data['detailsReference'], 'String');
            }
            if (data.hasOwnProperty('line')) {
                obj['line'] = VTApiPlaneraResaWebV4ModelsPositionsLineDetailsApiModel.constructFromObject(data['line']);
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], [VTApiPlaneraResaCoreModelsNote]);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('direction')) {
                obj['direction'] = ApiClient.convertToType(data['direction'], 'String');
            }
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['detailsReference'] && !(typeof data['detailsReference'] === 'string' || data['detailsReference'] instanceof String)) {
            throw new Error("Expected the field `detailsReference` to be a primitive type in the JSON string but got " + data['detailsReference']);
        }
        // validate the optional field `line`
        if (data['line']) { // data not null
          VTApiPlaneraResaWebV4ModelsPositionsLineDetailsApiModel.validateJSON(data['line']);
        }
        if (data['notes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['notes'])) {
                throw new Error("Expected the field `notes` to be an array in the JSON data but got " + data['notes']);
            }
            // validate the optional field `notes` (array)
            for (const item of data['notes']) {
                VTApiPlaneraResaCoreModelsNote.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['direction'] && !(typeof data['direction'] === 'string' || data['direction'] instanceof String)) {
            throw new Error("Expected the field `direction` to be a primitive type in the JSON string but got " + data['direction']);
        }

        return true;
    }


}



/**
 * Journey reference
 * @member {String} detailsReference
 */
VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel.prototype['detailsReference'] = undefined;

/**
 * @member {module:model/VTApiPlaneraResaWebV4ModelsPositionsLineDetailsApiModel} line
 */
VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel.prototype['line'] = undefined;

/**
 * Journey notes
 * @member {Array.<module:model/VTApiPlaneraResaCoreModelsNote>} notes
 */
VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel.prototype['notes'] = undefined;

/**
 * Journey name
 * @member {String} name
 */
VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel.prototype['name'] = undefined;

/**
 * Journey direction
 * @member {String} direction
 */
VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel.prototype['direction'] = undefined;

/**
 * Current latitude of journey
 * @member {Number} latitude
 */
VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel.prototype['latitude'] = undefined;

/**
 * Current longitude of journey
 * @member {Number} longitude
 */
VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel.prototype['longitude'] = undefined;






export default VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel;

