/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class VTApiPlaneraResaWebV4ModelsOccupancyInformationSource.
* @enum {}
* @readonly
*/
export default class VTApiPlaneraResaWebV4ModelsOccupancyInformationSource {
    
        /**
         * value: "prediction"
         * @const
         */
        "prediction" = "prediction";

    
        /**
         * value: "realtime"
         * @const
         */
        "realtime" = "realtime";

    

    /**
    * Returns a <code>VTApiPlaneraResaWebV4ModelsOccupancyInformationSource</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/VTApiPlaneraResaWebV4ModelsOccupancyInformationSource} The enum <code>VTApiPlaneraResaWebV4ModelsOccupancyInformationSource</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

