/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver from './VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver';
import VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation from './VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation';

/**
 * The VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel model module.
 * @module model/VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel
 * @version v4
 */
class VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel {
    /**
     * Constructs a new <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel</code>.
     * Represents a segment of a departure access link, arrival access link or destination link.
     * @alias module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel
     */
    constructor() { 
        
        VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel} obj Optional instance to populate.
     * @return {module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel} The populated <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('maneuver')) {
                obj['maneuver'] = VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver.constructFromObject(data['maneuver']);
            }
            if (data.hasOwnProperty('orientation')) {
                obj['orientation'] = VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation.constructFromObject(data['orientation']);
            }
            if (data.hasOwnProperty('maneuverDescription')) {
                obj['maneuverDescription'] = ApiClient.convertToType(data['maneuverDescription'], 'String');
            }
            if (data.hasOwnProperty('distanceInMeters')) {
                obj['distanceInMeters'] = ApiClient.convertToType(data['distanceInMeters'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['maneuverDescription'] && !(typeof data['maneuverDescription'] === 'string' || data['maneuverDescription'] instanceof String)) {
            throw new Error("Expected the field `maneuverDescription` to be a primitive type in the JSON string but got " + data['maneuverDescription']);
        }

        return true;
    }


}



/**
 * Segment name.
 * @member {String} name
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel.prototype['name'] = undefined;

/**
 * @member {module:model/VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver} maneuver
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel.prototype['maneuver'] = undefined;

/**
 * @member {module:model/VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation} orientation
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel.prototype['orientation'] = undefined;

/**
 * Description for the maneuver.
 * @member {String} maneuverDescription
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel.prototype['maneuverDescription'] = undefined;

/**
 * Distance for this segment in meter.
 * @member {Number} distanceInMeters
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel.prototype['distanceInMeters'] = undefined;






export default VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkSegmentApiModel;

