/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VTApiPlaneraResaCoreModelsLocationType from './VTApiPlaneraResaCoreModelsLocationType';
import VTApiPlaneraResaCoreModelsNote from './VTApiPlaneraResaCoreModelsNote';

/**
 * The VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel model module.
 * @module model/VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel
 * @version v4
 */
class VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel {
    /**
     * Constructs a new <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel</code>.
     * Information about an endpoint on an access link.
     * @alias module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel
     * @param name {String} The location name.
     * @param locationType {module:model/VTApiPlaneraResaCoreModelsLocationType} 
     * @param plannedTime {String} The planned time in RFC 3339 format.
     */
    constructor(name, locationType, plannedTime) { 
        
        VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel.initialize(this, name, locationType, plannedTime);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, locationType, plannedTime) { 
        obj['name'] = name;
        obj['locationType'] = locationType;
        obj['plannedTime'] = plannedTime;
    }

    /**
     * Constructs a <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel} obj Optional instance to populate.
     * @return {module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel} The populated <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel();

            if (data.hasOwnProperty('gid')) {
                obj['gid'] = ApiClient.convertToType(data['gid'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('locationType')) {
                obj['locationType'] = VTApiPlaneraResaCoreModelsLocationType.constructFromObject(data['locationType']);
            }
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
            }
            if (data.hasOwnProperty('plannedTime')) {
                obj['plannedTime'] = ApiClient.convertToType(data['plannedTime'], 'String');
            }
            if (data.hasOwnProperty('estimatedTime')) {
                obj['estimatedTime'] = ApiClient.convertToType(data['estimatedTime'], 'String');
            }
            if (data.hasOwnProperty('estimatedOtherwisePlannedTime')) {
                obj['estimatedOtherwisePlannedTime'] = ApiClient.convertToType(data['estimatedOtherwisePlannedTime'], 'String');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], [VTApiPlaneraResaCoreModelsNote]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['gid'] && !(typeof data['gid'] === 'string' || data['gid'] instanceof String)) {
            throw new Error("Expected the field `gid` to be a primitive type in the JSON string but got " + data['gid']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['plannedTime'] && !(typeof data['plannedTime'] === 'string' || data['plannedTime'] instanceof String)) {
            throw new Error("Expected the field `plannedTime` to be a primitive type in the JSON string but got " + data['plannedTime']);
        }
        // ensure the json data is a string
        if (data['estimatedTime'] && !(typeof data['estimatedTime'] === 'string' || data['estimatedTime'] instanceof String)) {
            throw new Error("Expected the field `estimatedTime` to be a primitive type in the JSON string but got " + data['estimatedTime']);
        }
        // ensure the json data is a string
        if (data['estimatedOtherwisePlannedTime'] && !(typeof data['estimatedOtherwisePlannedTime'] === 'string' || data['estimatedOtherwisePlannedTime'] instanceof String)) {
            throw new Error("Expected the field `estimatedOtherwisePlannedTime` to be a primitive type in the JSON string but got " + data['estimatedOtherwisePlannedTime']);
        }
        if (data['notes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['notes'])) {
                throw new Error("Expected the field `notes` to be an array in the JSON data but got " + data['notes']);
            }
            // validate the optional field `notes` (array)
            for (const item of data['notes']) {
                VTApiPlaneraResaCoreModelsNote.validateJSON(item);
            };
        }

        return true;
    }


}

VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel.RequiredProperties = ["name", "locationType", "plannedTime"];

/**
 * The 16-digit Västtrafik gid.
 * @member {String} gid
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel.prototype['gid'] = undefined;

/**
 * The location name.
 * @member {String} name
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel.prototype['name'] = undefined;

/**
 * @member {module:model/VTApiPlaneraResaCoreModelsLocationType} locationType
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel.prototype['locationType'] = undefined;

/**
 * The WGS84 latitude of the location.
 * @member {Number} latitude
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel.prototype['latitude'] = undefined;

/**
 * The WGS84 longitude of the location.
 * @member {Number} longitude
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel.prototype['longitude'] = undefined;

/**
 * The planned time in RFC 3339 format.
 * @member {String} plannedTime
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel.prototype['plannedTime'] = undefined;

/**
 * The estimated time in RFC 3339 format.
 * @member {String} estimatedTime
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel.prototype['estimatedTime'] = undefined;

/**
 * The best known time of the link in RFC 3339 format. Is EstimatedTime if exists, otherwise PlannedTime.
 * @member {String} estimatedOtherwisePlannedTime
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel.prototype['estimatedOtherwisePlannedTime'] = undefined;

/**
 * An ordered list (most important first) of notes related to the end point.
 * @member {Array.<module:model/VTApiPlaneraResaCoreModelsNote>} notes
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel.prototype['notes'] = undefined;






export default VTApiPlaneraResaWebV4ModelsJourneyDetailsLinkEndpointApiModel;

