/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VTApiPlaneraResaCoreModelsTimeValidityType from './VTApiPlaneraResaCoreModelsTimeValidityType';
import VTApiPlaneraResaCoreModelsTimeValidityUnit from './VTApiPlaneraResaCoreModelsTimeValidityUnit';

/**
 * The VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel model module.
 * @module model/VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel
 * @version v4
 */
class VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel {
    /**
     * Constructs a new <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel</code>.
     * Information about the time validity of a ticket suggestion.
     * @alias module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel
     */
    constructor() { 
        
        VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel} obj Optional instance to populate.
     * @return {module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel} The populated <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel();

            if (data.hasOwnProperty('type')) {
                obj['type'] = VTApiPlaneraResaCoreModelsTimeValidityType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = VTApiPlaneraResaCoreModelsTimeValidityUnit.constructFromObject(data['unit']);
            }
            if (data.hasOwnProperty('fromDate')) {
                obj['fromDate'] = ApiClient.convertToType(data['fromDate'], 'String');
            }
            if (data.hasOwnProperty('toDate')) {
                obj['toDate'] = ApiClient.convertToType(data['toDate'], 'String');
            }
            if (data.hasOwnProperty('fromDateTime')) {
                obj['fromDateTime'] = ApiClient.convertToType(data['fromDateTime'], 'String');
            }
            if (data.hasOwnProperty('toDateTime')) {
                obj['toDateTime'] = ApiClient.convertToType(data['toDateTime'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['fromDate'] && !(typeof data['fromDate'] === 'string' || data['fromDate'] instanceof String)) {
            throw new Error("Expected the field `fromDate` to be a primitive type in the JSON string but got " + data['fromDate']);
        }
        // ensure the json data is a string
        if (data['toDate'] && !(typeof data['toDate'] === 'string' || data['toDate'] instanceof String)) {
            throw new Error("Expected the field `toDate` to be a primitive type in the JSON string but got " + data['toDate']);
        }
        // ensure the json data is a string
        if (data['fromDateTime'] && !(typeof data['fromDateTime'] === 'string' || data['fromDateTime'] instanceof String)) {
            throw new Error("Expected the field `fromDateTime` to be a primitive type in the JSON string but got " + data['fromDateTime']);
        }
        // ensure the json data is a string
        if (data['toDateTime'] && !(typeof data['toDateTime'] === 'string' || data['toDateTime'] instanceof String)) {
            throw new Error("Expected the field `toDateTime` to be a primitive type in the JSON string but got " + data['toDateTime']);
        }

        return true;
    }


}



/**
 * @member {module:model/VTApiPlaneraResaCoreModelsTimeValidityType} type
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel.prototype['type'] = undefined;

/**
 * The amount of the unit specified by the Unit property. Always used together with the Unit property.
 * @member {Number} amount
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel.prototype['amount'] = undefined;

/**
 * @member {module:model/VTApiPlaneraResaCoreModelsTimeValidityUnit} unit
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel.prototype['unit'] = undefined;

/**
 * The from date of a date interval specified in RFC 3339 format. Always used together with the  ToDate property.
 * @member {String} fromDate
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel.prototype['fromDate'] = undefined;

/**
 * The to date of a date interval specified in RFC 3339 format. Always used together with the  FromDate property.
 * @member {String} toDate
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel.prototype['toDate'] = undefined;

/**
 * The from time of a datetime interval specified in RFC 3339 format. Always used together with  the ToDateTime property.
 * @member {String} fromDateTime
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel.prototype['fromDateTime'] = undefined;

/**
 * The to time of a datetime interval specified in RFC 3339 format. Always used together with  the FromDateTime property.
 * @member {String} toDateTime
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel.prototype['toDateTime'] = undefined;






export default VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel;

