/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VTApiPlaneraResaWebV4ModelsCoordinateApiModel model module.
 * @module model/VTApiPlaneraResaWebV4ModelsCoordinateApiModel
 * @version v4
 */
class VTApiPlaneraResaWebV4ModelsCoordinateApiModel {
    /**
     * Constructs a new <code>VTApiPlaneraResaWebV4ModelsCoordinateApiModel</code>.
     * Information about the coordinates
     * @alias module:model/VTApiPlaneraResaWebV4ModelsCoordinateApiModel
     */
    constructor() { 
        
        VTApiPlaneraResaWebV4ModelsCoordinateApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VTApiPlaneraResaWebV4ModelsCoordinateApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VTApiPlaneraResaWebV4ModelsCoordinateApiModel} obj Optional instance to populate.
     * @return {module:model/VTApiPlaneraResaWebV4ModelsCoordinateApiModel} The populated <code>VTApiPlaneraResaWebV4ModelsCoordinateApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VTApiPlaneraResaWebV4ModelsCoordinateApiModel();

            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
            }
            if (data.hasOwnProperty('elevation')) {
                obj['elevation'] = ApiClient.convertToType(data['elevation'], 'Number');
            }
            if (data.hasOwnProperty('isOnTripLeg')) {
                obj['isOnTripLeg'] = ApiClient.convertToType(data['isOnTripLeg'], 'Boolean');
            }
            if (data.hasOwnProperty('isTripLegStart')) {
                obj['isTripLegStart'] = ApiClient.convertToType(data['isTripLegStart'], 'Boolean');
            }
            if (data.hasOwnProperty('isTripLegStop')) {
                obj['isTripLegStop'] = ApiClient.convertToType(data['isTripLegStop'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VTApiPlaneraResaWebV4ModelsCoordinateApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VTApiPlaneraResaWebV4ModelsCoordinateApiModel</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * The latitude of this position (WGS84).
 * @member {Number} latitude
 */
VTApiPlaneraResaWebV4ModelsCoordinateApiModel.prototype['latitude'] = undefined;

/**
 * The longitude of this position (WGS84).
 * @member {Number} longitude
 */
VTApiPlaneraResaWebV4ModelsCoordinateApiModel.prototype['longitude'] = undefined;

/**
 * The elevation of this position (WGS84).
 * @member {Number} elevation
 */
VTApiPlaneraResaWebV4ModelsCoordinateApiModel.prototype['elevation'] = undefined;

/**
 * The coordinate is on the tripleg.
 * @member {Boolean} isOnTripLeg
 */
VTApiPlaneraResaWebV4ModelsCoordinateApiModel.prototype['isOnTripLeg'] = undefined;

/**
 * The coordinate is on the first call of the leg.
 * @member {Boolean} isTripLegStart
 */
VTApiPlaneraResaWebV4ModelsCoordinateApiModel.prototype['isTripLegStart'] = undefined;

/**
 * The coordinate is on the last call of the leg.
 * @member {Boolean} isTripLegStop
 */
VTApiPlaneraResaWebV4ModelsCoordinateApiModel.prototype['isTripLegStop'] = undefined;






export default VTApiPlaneraResaWebV4ModelsCoordinateApiModel;

