/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VTApiPlaneraResaWebV4ModelsPunchConfigurationDurationUnitApiModel from './VTApiPlaneraResaWebV4ModelsPunchConfigurationDurationUnitApiModel';

/**
 * The VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel model module.
 * @module model/VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel
 * @version v4
 */
class VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel {
    /**
     * Constructs a new <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel</code>.
     * Describes the duration of validity of a single punch.
     * @alias module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel
     */
    constructor() { 
        
        VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel} obj Optional instance to populate.
     * @return {module:model/VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel} The populated <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel();

            if (data.hasOwnProperty('unit')) {
                obj['unit'] = VTApiPlaneraResaWebV4ModelsPunchConfigurationDurationUnitApiModel.constructFromObject(data['unit']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {module:model/VTApiPlaneraResaWebV4ModelsPunchConfigurationDurationUnitApiModel} unit
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel.prototype['unit'] = undefined;

/**
 * Duration of validity of a single punch.
 * @member {Number} amount
 */
VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel.prototype['amount'] = undefined;






export default VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel;

