/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import VTApiPlaneraResaCoreModelsPositionTransportMode from '../model/VTApiPlaneraResaCoreModelsPositionTransportMode';
import VTApiPlaneraResaWebV4ModelsApiError from '../model/VTApiPlaneraResaWebV4ModelsApiError';
import VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel from '../model/VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel';

/**
* Positions service.
* @module api/PositionsApi
* @version v4
*/
export default class PositionsApi {

    /**
    * Constructs a new PositionsApi. 
    * @alias module:api/PositionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the positionsGet operation.
     * @callback module:api/PositionsApi~positionsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns journey positions within a bounding box
     * Sample request:        GET /positions?lowerLeftLat=57.721723&lowerLeftLong=12.011882&upperRightLat=57.737549&upperRightLong=12.039268&limit=100
     * @param {Number} lowerLeftLat Lower left latitude of bounding box.
     * @param {Number} lowerLeftLong Lower left longitude of bounding box.
     * @param {Number} upperRightLat Upper right latitude of bounding box.
     * @param {Number} upperRightLong Upper right longitude of bounding box.
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/VTApiPlaneraResaCoreModelsPositionTransportMode>} opts.transportModes The transport modes to include when searching for journeys, if none specified all transport modes are included.
     * @param {Array.<String>} opts.detailsReferences Filter journeys by one or more journey details reference.
     * @param {Array.<String>} opts.lineDesignations Only journeys running the given lineDesignations (case sensitive) are part of the result.
     * @param {Number} opts.limit Maximum number of journeys in response. Range from 1 to 200. Defaults to 100 (default to 100)
     * @param {module:api/PositionsApi~positionsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel>}
     */
    positionsGet(lowerLeftLat, lowerLeftLong, upperRightLat, upperRightLong, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'lowerLeftLat' is set
      if (lowerLeftLat === undefined || lowerLeftLat === null) {
        throw new Error("Missing the required parameter 'lowerLeftLat' when calling positionsGet");
      }
      // verify the required parameter 'lowerLeftLong' is set
      if (lowerLeftLong === undefined || lowerLeftLong === null) {
        throw new Error("Missing the required parameter 'lowerLeftLong' when calling positionsGet");
      }
      // verify the required parameter 'upperRightLat' is set
      if (upperRightLat === undefined || upperRightLat === null) {
        throw new Error("Missing the required parameter 'upperRightLat' when calling positionsGet");
      }
      // verify the required parameter 'upperRightLong' is set
      if (upperRightLong === undefined || upperRightLong === null) {
        throw new Error("Missing the required parameter 'upperRightLong' when calling positionsGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'lowerLeftLat': lowerLeftLat,
        'lowerLeftLong': lowerLeftLong,
        'upperRightLat': upperRightLat,
        'upperRightLong': upperRightLong,
        'transportModes': this.apiClient.buildCollectionParam(opts['transportModes'], 'multi'),
        'detailsReferences': this.apiClient.buildCollectionParam(opts['detailsReferences'], 'multi'),
        'lineDesignations': this.apiClient.buildCollectionParam(opts['lineDesignations'], 'multi'),
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['auth'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [VTApiPlaneraResaWebV4ModelsPositionsJourneyPositionApiModel];
      return this.apiClient.callApi(
        '/positions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
