/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PlaneraResa);
  }
}(this, function(expect, PlaneraResa) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PlaneraResa.JourneysApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JourneysApi', function() {
    describe('journeysDetailsReferenceDetailsGet', function() {
      it('should call journeysDetailsReferenceDetailsGet successfully', function(done) {
        //uncomment below and update the code to test journeysDetailsReferenceDetailsGet
        //instance.journeysDetailsReferenceDetailsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('journeysGet', function() {
      it('should call journeysGet successfully', function(done) {
        //uncomment below and update the code to test journeysGet
        //instance.journeysGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('journeysReconstructGet', function() {
      it('should call journeysReconstructGet successfully', function(done) {
        //uncomment below and update the code to test journeysReconstructGet
        //instance.journeysReconstructGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('journeysValidTimeIntervalGet', function() {
      it('should call journeysValidTimeIntervalGet successfully', function(done) {
        //uncomment below and update the code to test journeysValidTimeIntervalGet
        //instance.journeysValidTimeIntervalGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
